version: "3"
services:
  mymongodb:
    image: mongo:latest
    container_name: "mymongodb"
    ports:
     - 27017:27017
  springboot-library1:
    image: library-demo-image1
    container_name: springboot-library1
    ports:
     - 9090:9090
    links:
      - mymongodb